# Generated by Django 3.2.9 on 2021-11-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='Published at')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('nick', models.CharField(max_length=128)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgs.image')),
            ],
        ),
    ]
