# Generated by Django 3.2.9 on 2021-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
