# Generated by Django 3.1.3 on 2020-12-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201214_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likeInComment',
            new_name='likecomment',
        ),
    ]
